use_frameworks!

platform :ios, '8.0'

target 'LxCustomAlert_Example' do
  pod 'LxCustomAlert', :path => '../'

  target 'LxCustomAlert_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
